/* tslint:disable */
/* eslint-disable */

/**
 * This class has been generated with this commend
 *  npx @openapitools/openapi-generator-cli generate -i https://finnhub.io/static/swagger.json -g typescript-axios -o ./src/api/finnhubService/ --skip-validate-spec --additional-properties=supportsES6=true,npmVersion=6.9.0,typescriptThreePlus=true
 *  After generating with this commend there is a need to change all the places that has the name "economic event" to "EconomicEvent"
 * */

/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from "./api";
export * from "./configuration";
